"""empty message

Revision ID: c543cb2c4946
Revises: dce64e00aaa5
Create Date: 2020-09-01 19:32:07.750818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c543cb2c4946'
down_revision = 'dce64e00aaa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento') as batch_operation:
        batch_operation.drop_column('coluna')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agendamento', sa.Column('coluna', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
