"""empty message

Revision ID: dce64e00aaa5
Revises: dd885d956736
Create Date: 2020-09-01 12:46:18.052931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dce64e00aaa5'
down_revision = 'dd885d956736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agendamento', sa.Column('coluna', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agendamento', 'coluna')
    # ### end Alembic commands ###
