"""empty message

Revision ID: dd885d956736
Revises: ad927d7265d8
Create Date: 2020-09-01 11:42:40.117810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd885d956736'
down_revision = 'ad927d7265d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agendamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipamento', sa.String(length=100), nullable=True),
    sa.Column('processo', sa.String(length=50), nullable=True),
    sa.Column('prazo', sa.String(length=20), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_calibracao', sa.DateTime(), nullable=True),
    sa.Column('data_registro', sa.DateTime(), nullable=False),
    sa.Column('laboratorio', sa.String(length=100), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agendamento')
    # ### end Alembic commands ###
